#services:
#  postgres:
#    container_name: postgres-container
#    image: postgres
#    environment:
#      POSTGRES_USER : Rahul
#      POSTGRES_PASSWORD : Rahul@7879
#      PGDATA: /data/postgres
#    volumes:
#      - postgres: /data/postgres
#    ports:
#      - "5432:5432"
#    networks:
#      - postgres
#    restart: unless-stopped
#
#  pgadmin:
#    container_name: pgadmin-container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${ PGADMIN_DEFAULT_EMAIL:-rahul3004rt@gmail.com}
#      PGADMIN_DEFAULT_PASSWORD: {PGADMIN_DEFAULT_PASSWORD:-Rahu@7879}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:var/lib/pgadmin
#    ports:
#      - "5050:80"
#    network:
#      - postgres
#    restart: unless-stopped
#networks:
#  postgres:
#    driver: bridge
#
#volumes:
#  postgres:
#  pgadmin:

services:
  postgres:
    container_name: postgres-container
    image: postgres
    environment:
      POSTGRES_USER: Rahul
      POSTGRES_PASSWORD: Rahul@7879
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin-container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-rahul3004rt@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-Rahu@7879}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:

volumes:
  postgres:
  pgadmin: